# Generated by Django 4.1.2 on 2023-07-25 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="receiver",
            new_name="recipient",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="sender",
            new_name="user",
        ),
    ]
