# Generated by Django 4.1.2 on 2023-07-27 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatpage_message_chat_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="user",
            new_name="sender",
        ),
    ]
