# Generated by Django 4.1.2 on 2023-07-27 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0004_rename_user_message_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatpage",
            name="name",
        ),
        migrations.RemoveField(
            model_name="message",
            name="chat_page",
        ),
        migrations.AddField(
            model_name="chatpage",
            name="contact",
            field=models.ForeignKey(
                default=18,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatpage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatpage",
            name="user",
            field=models.ForeignKey(
                default=15,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_pages",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
