# Generated by Django 4.1.2 on 2023-08-05 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_room"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatPage",
        ),
    ]
