# Generated by Django 4.1.2 on 2023-08-11 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_delete_chatpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Room",
        ),
    ]
