# Generated by Django 4.1.2 on 2023-05-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "slug",
                    models.SlugField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to="blog.author",
                    ),
                ),
            ],
        ),
    ]
