# Generated by Django 4.1.2 on 2023-05-28 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="subscribers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="author",
            name="subscriptions_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="blog.author",
            ),
        ),
    ]
