# Generated by Django 4.1.2 on 2023-06-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_article"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="author",
            new_name="target",
        ),
        migrations.AddField(
            model_name="author",
            name="articles_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="author",
            name="subscribers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="author",
            name="subscriptions_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="blog.author",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=55),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("subscriber", "target")},
        ),
    ]
