# Generated by Django 4.1.2 on 2023-06-01 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_author_subscribers_count_author_subscriptions_count_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="author",
            new_name="target",
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("subscriber", "target")},
        ),
    ]
