# Generated by Django 4.1.2 on 2023-06-05 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_rename_author_subscription_target_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscription",
            new_name="Relation",
        ),
    ]
