# Generated by Django 4.1.2 on 2023-06-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_author_created_at_subscription_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="author",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
