# Generated by Django 4.1.2 on 2023-06-09 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_rename_subscription_relation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="subscribers_count",
        ),
        migrations.RemoveField(
            model_name="author",
            name="subscriptions_count",
        ),
    ]
