# Generated by Django 4.1.2 on 2023-06-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_remove_author_subscribers_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="subscribers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="author",
            name="subscriptions_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
