# Generated by Django 4.1.2 on 2023-06-19 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_alter_article_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="author",
            new_name="target",
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("subscriber", "target")},
        ),
    ]
