# Generated by Django 4.1.2 on 2023-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_rename_author_subscription_target_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="articles_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
